# 지식 그래프 RAG와 자율 검색 에이전트 (답안)

**교과목**: 지식 그래프 RAG와 자율 검색 에이전트  
**과제**: 농약 안전사용 상담 — Graph RAG / Agentic RAG / CRAG / RAG Fusion  
**권장 파일명**: `지식그래프RAG_자율검색에이전트_답안.ipynb`

정형 농약제품 목록(엑셀)과 농약안전정보시스템 웹 문서를 결합해, 단원 예제 01~04의 네 전략을 **같은 코퍼스** 위에서 구현·비교한다.

| 전략 | 역할 | 참고 예제 |
|---|---|---|
| Graph RAG | 제품·작물·병해충·회사 관계를 k홉 순회 | `01_Graph RAG - 관계형 검색 원리.ipynb` |
| Agentic RAG | 벡터/그래프/안전문서 도구를 Agent가 자율 선택 | `02_Agentic RAG - Agent가 검색 전략 자율 결정.ipynb` |
| Self-Corrective RAG | 검색 채점 → 질의 재작성 → 웹 문서로 전환 | `03_Self-Corrective RAG - 검색 결과 자기평가·재시도.ipynb` |
| RAG Fusion | Multi-Query + RRF, Dense+BM25 하이브리드 | `04_RAG Fusion - 앙상블 검색 통합 기법.ipynb` |

**제공 자료** (`실습과제/`)

- `20260823_농약제품 목록.xlsx` — 제품×작물×병해충 관계 레코드 (원본 약 14만 행 → 지정 작물·상표 샘플만 사용)
- `농약 관련 웹 문서 수집용 주소.txt` — 농약 정의·중독·응급처치·주의사항·사용 후 관리

API 키는 `C:\env\.env`에서만 읽고, 값은 출력하지 않는다.

## 0. 환경 설정

`C:\env\.env`에서 `OPENAI_API_KEY`를 읽는다.

In [1]:
# 단원 예제와 동일한 의존성 (이미 있으면 건너뛴다)
# rank_bm25=키워드 검색, networkx=지식 그래프, faiss-cpu=벡터스토어,
# langgraph=Agent/CRAG 상태머신, langchain-classic=EnsembleRetriever
%pip install -q rank_bm25 networkx beautifulsoup4 faiss-cpu langgraph langchain-openai langchain-community langchain-classic pandas openpyxl python-dotenv lxml

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# 표준 라이브러리와 데이터프레임·환경변수 로더를 불러온다.
import os
import re
import time
import warnings
from collections import defaultdict
from pathlib import Path
from typing import Annotated, Dict, List, Tuple, TypedDict
from urllib.parse import urlparse, parse_qs

import pandas as pd
from dotenv import load_dotenv

# 실습 출력에 의존성 경고가 섞이지 않게 숨긴다.
warnings.filterwarnings("ignore")

# API 키는 과제 폴더가 아니라 공유 env 파일에서만 읽는다. 키 값은 출력하지 않는다.
ENV_PATH = Path(r"C:\env\.env")
loaded = load_dotenv(dotenv_path=ENV_PATH, override=True)
print(f"[env] loaded={loaded} path={ENV_PATH}")

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
assert OPENAI_API_KEY, r"OPENAI_API_KEY 가 C:\env\.env 에 없습니다."
print("OPENAI_API_KEY: 로드 완료 (값은 출력하지 않음)")

# WebBaseLoader / requests 가 빈 User-Agent 로 거부되지 않도록 설정
# 일부 공공 사이트는 User-Agent가 없으면 403을 돌려준다.
os.environ.setdefault(
    "USER_AGENT",
    "Mozilla/5.0 (compatible; PesticideRAG-Lab/1.0; +https://psis.rda.go.kr)",
)

[env] loaded=True path=C:\env\.env
OPENAI_API_KEY: 로드 완료 (값은 출력하지 않음)

'Mozilla/5.0 (compatible; PesticideRAG-Lab/1.0; +https://psis.rda.go.kr)'

In [3]:
# 이후 모든 검색 전략 비교에서 같은 임베딩·생성 모델을 쓴다.
EMBEDDING_MODEL = "text-embedding-3-small"
LLM_MODEL = "gpt-4o-mini"

# 원본 엑셀은 약 14만 행이므로 지정 작물만 남기고, 작물별 상표 수를 제한한다.
TARGET_CROPS = ["고추", "벼", "토마토", "사과", "배추"]
MAX_BRANDS_PER_CROP = 25
RANDOM_STATE = 42

# TOP_N: 벡터 검색이 답변에 넘기는 문서 수
# GRAPH_HOPS: seed에서 양방향으로 따라갈 최대 관계 거리
# MAX_GRAPH_EDGES: 프롬프트에 넣을 트리플 상한(너무 길면 근거가 희석됨)
# MAX_CRAG_RETRIES: 관련 문서가 없을 때 질의를 고쳐 다시 검색하는 횟수
TOP_N = 4
GRAPH_HOPS = 2
MAX_GRAPH_EDGES = 80
MAX_CRAG_RETRIES = 2


def resolve_assignment_dir() -> Path:
    """cwd 또는 상위 폴더에서 엑셀·URL 파일이 있는 실습과제 폴더를 찾는다."""
    # 노트북을 상위 폴더에서 실행해도 자료 파일을 찾도록, 마커 파일 존재 여부로 폴더를 판별한다.
    markers = ["20260823_농약제품 목록.xlsx", "농약 관련 웹 문서 수집용 주소.txt"]
    for p in [Path.cwd(), *Path.cwd().parents]:
        if all((p / m).exists() for m in markers):
            return p
        inner = p / "실습과제"
        if all((inner / m).exists() for m in markers):
            return inner
    return Path.cwd()


ASSIGN_DIR = resolve_assignment_dir()
EXCEL_PATH = ASSIGN_DIR / "20260823_농약제품 목록.xlsx"
URL_FILE = ASSIGN_DIR / "농약 관련 웹 문서 수집용 주소.txt"

print("ASSIGN_DIR :", ASSIGN_DIR)
print("EXCEL_PATH :", EXCEL_PATH.exists(), EXCEL_PATH.name)
print("URL_FILE   :", URL_FILE.exists(), URL_FILE.name)

ASSIGN_DIR : c:\Users\storm\Desktop\[전남ICT]생성형 AI 기반 스마트 농업 통합 서비스 개발\실습소스\05_LangChain 기반 AI Agent 활용\04_지식 그래프 RAG와 자율 검색 에이전트\실습과제
EXCEL_PATH : True 20260823_농약제품 목록.xlsx
URL_FILE   : True 농약 관련 웹 문서 수집용 주소.txt

In [4]:
# ChatOpenAI: 답변 생성·도구 호출 / OpenAIEmbeddings: 문서·질문 벡터화
# FAISS: 인메모리 벡터스토어 / Document: RAG의 기본 문서 단위
from langchain_openai import ChatOpenAI, OpenAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser

# temperature=0 으로 전략 비교 때 생성 쪽 변동을 줄인다.
llm = ChatOpenAI(model=LLM_MODEL, temperature=0, api_key=OPENAI_API_KEY)
embeddings = OpenAIEmbeddings(model=EMBEDDING_MODEL, api_key=OPENAI_API_KEY)
print(f"LLM={LLM_MODEL}, embedding={EMBEDDING_MODEL}")

LLM=gpt-4o-mini, embedding=text-embedding-3-small

## 1. 데이터 준비

### [1-1] 농약제품 목록 로드·샘플링

원본은 약 14만 행이므로 **지정 작물로 필터한 뒤 작물별 상표명 25개**만 사용한다.  
한 상표의 모든 적용병해충 행은 유지해, 그래프에서 `제품 → 병해충` 관계가 살아 있게 한다.

In [5]:
# 엑셀 작물명을 실습용 작물군으로 묶는다. '고추(단고추류 포함)', '방울토마토'처럼
# 표기가 달라도 같은 군으로 보고, 대상이 아니면 None을 반환해 이후 필터에서 제외한다.
def crop_group(name: str) -> str | None:
    n = str(name).strip()
    for crop in TARGET_CROPS:
        if n == crop or n.startswith(crop + "(") or n.startswith(crop + " "):
            return crop
        if crop == "토마토" and "토마토" in n:
            return crop
        if crop == "고추" and n.startswith("고추"):
            return crop
    return None


print("엑셀 로드 중... (약 14만 행, 수십 초 소요될 수 있음)")
t0 = time.time()
# header=2: 시트 상단 제목·빈 줄을 건너뛰고 실제 컬럼행을 헤더로 사용한다.
raw = pd.read_excel(EXCEL_PATH, header=2)
print(f"원본 행 수: {len(raw):,}  ({time.time() - t0:.1f}s)")
print("컬럼:", list(raw.columns))

df = raw.copy()
# 대상 작물이 아니거나 상표명이 비어 있는 행은 그래프·검색에 쓰지 않는다.
df["작물군"] = df["작물명"].map(crop_group)
df = df.dropna(subset=["작물군", "상표명"]).copy()
df["상표명"] = df["상표명"].astype(str).str.strip()
df = df[df["상표명"].ne("") & df["상표명"].ne("nan")]

sampled_frames = []
for crop in TARGET_CROPS:
    part = df[df["작물군"] == crop]
    # 작물별로 상표명을 최대 25개만 뽑되, 그 상표의 병해충 행은 모두 남긴다.
    # 한 상표가 여러 병해충에 등록된 관계가 그래프의 CONTROLS 엣지가 된다.
    brands = (
        part["상표명"]
        .drop_duplicates()
        .sample(n=min(MAX_BRANDS_PER_CROP, part["상표명"].nunique()), random_state=RANDOM_STATE)
    )
    sampled_frames.append(part[part["상표명"].isin(set(brands))])

products = pd.concat(sampled_frames, ignore_index=True)
print("\n작물군별 샘플 행 수 / 상표 수")
print(
    products.groupby("작물군").agg(행수=("상표명", "size"), 상표수=("상표명", "nunique"))
)
print(f"\n샘플 전체: {len(products):,}행, 상표 {products['상표명'].nunique()}개")
products.head(3)

엑셀 로드 중... (약 14만 행, 수십 초 소요될 수 있음)
원본 행 수: 144,453  (40.1s)
컬럼: ['등록번호', '구분', '작물명', '적용병해충', '품목명', '일반명', '주성분함량', '상표명', '인축독성', '어독성', '용도', '등록일', '작용기작', '희석배수', '사용량', '사용적기', '사용방법', '안전사용시기', '안전사용횟수', '제형', '회사명']

작물군별 샘플 행 수 / 상표 수
      행수  상표수
작물군
고추    84   25
배추    61   25
벼    116   25
사과    79   25
토마토   43   25

샘플 전체: 383행, 상표 125개

,등록번호,구분,작물명,적용병해충,품목명,일반명,주성분함량,상표명,인축독성,어독성,...,작용기작,희석배수,사용량,사용적기,사용방법,안전사용시기,안전사용횟수,제형,회사명,작물군
0,8-살균-236,제조,고추(단고추류 포함),역병,클로로탈로닐.크레속심메틸 액상수화제,Chlorothalonil+Kresoxim-methyl,42(35+7)%,경탄,Ⅳ급(저독성),Ⅰ급,...,카+다3,1000배,-,발병 전 또는 장마 직전부터,경엽처리,수확3일전,3회,액상수화제,(주)농협케미컬,고추
1,8-살균-236,제조,고추(단고추류 포함),갈색점무늬병,클로로탈로닐.크레속심메틸 액상수화제,Chlorothalonil+Kresoxim-methyl,42(35+7)%,경탄,Ⅳ급(저독성),Ⅰ급,...,카+다3,1000배,-,발병 초부터,경엽처리,수확3일전,3회,액상수화제,(주)농협케미컬,고추
2,8-살균-236,제조,고추(단고추류 포함),탄저병,클로로탈로닐.크레속심메틸 액상수화제,Chlorothalonil+Kresoxim-methyl,42(35+7)%,경탄,Ⅳ급(저독성),Ⅰ급,...,카+다3,1000배,-,발병 초부터,경엽처리,수확3일전,3회,액상수화제,(주)농협케미컬,고추

### [1-2] 제품 행 → 사실 문장 (벡터 검색용)

In [6]:
# 행에서 컬럼 값을 문자열로 꺼낸다. 결측·공백은 빈 문자열로 통일한다.
def cell(row, col) -> str:
    v = row.get(col, "")
    if pd.isna(v):
        return ""
    return str(v).strip()


# 한 제품 행을 벡터 검색용 사실 문장으로 펼친다.
# 컬럼이 분리된 표는 임베딩이 관계를 못 잡을 수 있어, 상표·작물·병해충·독성·회사를 한 문장에 모은다.
def row_to_fact(row) -> str:
    brand = cell(row, "상표명")
    crop = cell(row, "작물명")
    pest = cell(row, "적용병해충")
    item = cell(row, "품목명")
    common = cell(row, "일반명")
    content = cell(row, "주성분함량")
    use = cell(row, "용도")
    tox = cell(row, "인축독성")
    fish = cell(row, "어독성")
    company = cell(row, "회사명")
    phi = cell(row, "안전사용시기")
    times = cell(row, "안전사용횟수")
    method = cell(row, "사용방법")
    timing = cell(row, "사용적기")
    form = cell(row, "제형")
    dilute = cell(row, "희석배수")
    amount = cell(row, "사용량")
    # 값이 있는 컬럼만 문장에 이어 붙여, 빈 칸이 검색 문맥을 흐리지 않게 한다.
    parts = [
        f"상표명 '{brand}'는 작물 '{crop}'의 '{pest}'에 사용하는 {use}제이다."
        if use else f"상표명 '{brand}'는 작물 '{crop}'의 '{pest}'에 사용한다."
    ]
    if item:
        parts.append(f"품목명은 {item}이다.")
    if common:
        extra = f"(함량 {content})" if content else ""
        parts.append(f"주성분(일반명)은 {common}{extra}이다.")
    if tox:
        parts.append(f"인축독성은 {tox}이다.")
    if fish:
        parts.append(f"어독성은 {fish}이다.")
    if company:
        parts.append(f"회사는 {company}이다.")
    if phi:
        parts.append(f"안전사용시기는 {phi}이다.")
    if times:
        parts.append(f"안전사용횟수는 {times}이다.")
    if method:
        parts.append(f"사용방법은 {method}이다.")
    if timing:
        parts.append(f"사용적기는 {timing}이다.")
    if form:
        parts.append(f"제형은 {form}이다.")
    if dilute and dilute != "-":
        parts.append(f"희석배수는 {dilute}이다.")
    if amount and amount != "-":
        parts.append(f"사용량은 {amount}이다.")
    return " ".join(parts)


# metadata는 출처 표시·분석용이고, 유사도 계산에는 page_content만 쓰인다.
product_docs: List[Document] = []
for i, row in products.iterrows():
    product_docs.append(
        Document(
            page_content=row_to_fact(row),
            metadata={
                "source": "product_excel",
                "doc_type": "product",
                "brand": cell(row, "상표명"),
                "crop": cell(row, "작물명"),
                "crop_group": row["작물군"],
                "pest": cell(row, "적용병해충"),
                "company": cell(row, "회사명"),
                "use": cell(row, "용도"),
                "toxicity": cell(row, "인축독성"),
            },
        )
    )

print(f"제품 사실 문장 수: {len(product_docs)}")
print("예시:\n", product_docs[0].page_content)

제품 사실 문장 수: 383
예시:
 상표명 '경탄'는 작물 '고추(단고추류 포함)'의 '역병'에 사용하는 살균제이다. 품목명은 클로로탈로닐.크레속심메틸 액상수화제이다. 주성분(일반명)은 Chlorothalonil+Kresoxim-methyl(함량 42(35+7)%)이다. 인축독성은 Ⅳ급(저독성)이다. 어독성은 Ⅰ급이다. 회사는 (주)농협케미컬이다. 안전사용시기는 수확3일전이다. 안전사용횟수는 3회이다. 사용방법은 경엽처리이다. 사용적기는 발병 전 또는 장마 직전부터이다. 제형은 액상수화제이다. 희석배수는 1000배이다.

### [1-3] 안전사용 웹 문서 수집·청킹

`농약 관련 웹 문서 수집용 주소.txt`에서 URL을 파싱한다.  
단원 `06_문서 로더.ipynb`의 `WebBaseLoader`를 쓰되, 본문이 비면 requests+BeautifulSoup로 재시도한다.

In [7]:
from langchain_community.document_loaders import WebBaseLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
import requests
from bs4 import BeautifulSoup


# 주소 파일은 '제목 줄 + URL 줄' 형식이다. URL이 나오기 직전 한글 줄을 페이지 제목으로 붙인다.
def parse_url_list(path: Path) -> List[Tuple[str, str]]:
    """(제목, url) 목록. 직전 비어 있지 않은 한글 줄을 제목으로 사용."""
    text = path.read_text(encoding="utf-8")
    items = []
    last_title = "농약 안전사용정보"
    for line in text.splitlines():
        line = line.strip().lstrip("-").strip()
        if not line:
            continue
        m = re.search(r"https?://\S+", line)
        if m:
            items.append((last_title, m.group(0).rstrip(").,]")))
        elif re.search(r"[가-힣]", line) and "http" not in line and not line.startswith("["):
            last_title = re.sub(r"^[0-9]+\.\s*", "", line).strip(" :")
    return items


url_items = parse_url_list(URL_FILE)
print("수집 대상:")
for title, url in url_items:
    print(f"  - {title}: {url}")


# 단원 문서 로더의 WebBaseLoader를 먼저 쓰고, 본문이 너무 짧으면 HTML을 직접 파싱한다.
def load_web_documents(items: List[Tuple[str, str]]) -> List[Document]:
    docs: List[Document] = []
    for title, url in items:
        page_text = ""
        try:
            loader = WebBaseLoader(web_path=url)
            loaded = loader.load()
            if loaded:
                page_text = loaded[0].page_content or ""
        except Exception as e:
            print(f"  WebBaseLoader 실패 ({title}): {e}")
        # 메뉴만 잡히거나 빈 페이지면 본문 길이가 매우 짧다. requests로 본문을 다시 긁는다.
        if len(page_text.strip()) < 200:
            try:
                resp = requests.get(
                    url,
                    headers={"User-Agent": os.environ["USER_AGENT"]},
                    timeout=30,
                )
                resp.raise_for_status()
                resp.encoding = resp.apparent_encoding or "utf-8"
                soup = BeautifulSoup(resp.text, "html.parser")
                # 스크립트·메뉴를 제거해 본문 위주로 남긴다.
                for tag in soup(["script", "style", "nav", "header", "footer", "noscript"]):
                    tag.decompose()
                page_text = soup.get_text("\n", strip=True)
            except Exception as e:
                print(f"  requests 재시도 실패 ({title}): {e}")
                continue
        lines = [ln.strip() for ln in page_text.splitlines() if ln.strip()]
        cleaned = "\n".join(lines)
        docs.append(
            Document(
                page_content=cleaned,
                metadata={"source": url, "title": title, "doc_type": "safety_web"},
            )
        )
        print(f"  수집 완료: {title} ({len(cleaned):,}자)")
    return docs


print("\n웹 문서 수집 중...")
web_raw_docs = load_web_documents(url_items)
# 700자 청크 + 120자 겹침: 응급처치 절차처럼 이어지는 문장이 잘려도 이웃 청크에 남게 한다.
splitter = RecursiveCharacterTextSplitter(chunk_size=700, chunk_overlap=120)
web_chunks = splitter.split_documents(web_raw_docs)
print(f"원문 {len(web_raw_docs)}페이지 → 청크 {len(web_chunks)}개")

수집 대상:
  - 농약이란?: https://psis.rda.go.kr/psis/cont/contentMain.ps?menuId=PS00384
  - 농약중독의 증상: https://psis.rda.go.kr/psis/cont/contentMain.ps?menuId=PS00960
  - 농약 중독 시 응급처치법: https://psis.rda.go.kr/psis/cont/contentMain.ps?menuId=PS00300
  - 농약 사용시 주의사항: https://psis.rda.go.kr/psis/cont/contentMain.ps?menuId=PS00961
  - 농약 사용후 관리: https://psis.rda.go.kr/psis/cont/contentMain.ps?menuId=PS00962

웹 문서 수집 중...
  수집 완료: 농약이란? (12,723자)
  수집 완료: 농약중독의 증상 (5,552자)
  수집 완료: 농약 중독 시 응급처치법 (3,867자)
  수집 완료: 농약 사용시 주의사항 (6,477자)
  수집 완료: 농약 사용후 관리 (3,440자)
원문 5페이지 → 청크 57개

### [1-4] 벡터스토어 구축

제품 KB / 안전사용 웹 / 통합 세 개를 만든다. CRAG는 제품 KB를 내부, 웹 청크를 외부 지식으로 쓴다.

In [8]:
print("임베딩 중...")
t0 = time.time()
# 제품 KB(상표·작물·병해충) / 웹(정의·중독·응급처치) / 통합(Fusion용 한 인덱스)
product_vs = FAISS.from_documents(product_docs, embeddings)
web_vs = FAISS.from_documents(web_chunks, embeddings)
combined_vs = FAISS.from_documents(product_docs + web_chunks, embeddings)
print(f"완료 ({time.time() - t0:.1f}s)")
print(f"제품 KB {len(product_docs)} / 웹 청크 {len(web_chunks)} / 통합 {len(product_docs)+len(web_chunks)}")


# 검색된 Document를 프롬프트에 넣을 불릿 텍스트로 바꾼다.
def format_docs(documents: List[Document]) -> str:
    return "\n".join(f"- {d.page_content}" for d in documents)


# 검색 문맥 밖의 일반 지식으로 약을 추천하지 못하게 하는 grounded 프롬프트.
GROUNDED_SYSTEM = (
    "당신은 농약 안전사용 상담 어시스턴트다. 아래 [근거]에 있는 내용만으로 답하라. "
    "근거에 없는 제품·용법·독성은 추측하지 말고 '주어진 자료만으로는 알 수 없다'고 답하라. "
    "답변 끝에 근거 유형(제품목록 / 지식그래프 / 안전사용 웹문서)을 한 줄로 밝혀라.\n\n[근거]\n{context}"
)
answer_prompt = ChatPromptTemplate.from_messages(
    [("system", GROUNDED_SYSTEM), ("human", "{question}")]
)
answer_chain = answer_prompt | llm | StrOutputParser()

임베딩 중...
완료 (2.8s)
제품 KB 383 / 웹 청크 57 / 통합 440

## 2. Graph RAG — 관계형 검색

엑셀 컬럼이 이미 (제품, 작물, 병해충, 성분, 회사, 독성) 관계이므로 **규칙 기반 트리플**로 그래프를 만든다.  
01번 예제의 LLM 트리플 추출은 비정형 문장용이며, 14만 행 전량에 호출하지 않는다.

관계 어휘: `USED_ON`, `CONTROLS`, `CONTAINS`, `MANUFACTURED_BY`, `HAS_TOXICITY`, `HAS_FISH_TOXICITY`, `HAS_USE`, `HAS_PHI`, `HAS_FORMULATION`

In [9]:
import networkx as nx


# 엑셀 한 행을 (주체, 관계, 객체) 트리플로 펼친다.
# 비정형 문장용 LLM 추출 대신, 이미 분리된 컬럼을 통제된 관계 어휘로 매핑한다.
def row_to_triples(row) -> List[Tuple[str, str, str]]:
    brand = cell(row, "상표명")
    triples = []

    def add(rel, obj):
        obj = str(obj).strip() if obj is not None and not pd.isna(obj) else ""
        if brand and obj and obj not in {"-", "nan"}:
            triples.append((brand, rel, obj))

    # 제품→작물 / 제품→병해충 / 제품→주성분 / 제품→회사 / 독성·용도·안전사용시기·제형
    add("USED_ON", cell(row, "작물명"))
    add("CONTROLS", cell(row, "적용병해충"))
    add("CONTAINS", cell(row, "일반명"))
    add("MANUFACTURED_BY", cell(row, "회사명"))
    add("HAS_TOXICITY", cell(row, "인축독성"))
    add("HAS_FISH_TOXICITY", cell(row, "어독성"))
    add("HAS_USE", cell(row, "용도"))
    add("HAS_PHI", cell(row, "안전사용시기"))
    add("HAS_FORMULATION", cell(row, "제형"))
    crop, pest = cell(row, "작물명"), cell(row, "적용병해충")
    if crop and pest:
        # 작물과 병해충을 직접 이으면 '고추 탄저병'처럼 두 seed가 한 서브그래프에 모인다.
        triples.append((crop, "AFFECTED_BY", pest))
    return triples


triples: List[Tuple[str, str, str]] = []
seen = set()
for _, row in products.iterrows():
    for t in row_to_triples(row):
        if t not in seen:
            seen.add(t)
            triples.append(t)

# MultiDiGraph: 같은 두 노드 사이에 관계가 여러 개여도 엣지를 모두 보관한다.
graph = nx.MultiDiGraph()
for s, r, o in triples:
    graph.add_edge(s, o, relation=r)

print(f"트리플 수: {len(triples)}")
print(f"노드 수: {graph.number_of_nodes()}, 엣지 수: {graph.number_of_edges()}")
print("관계 종류:", sorted({r for _, r, _ in triples}))
print("\n트리플 예시:")
for t in triples[:8]:
    print(f"  ({t[0]}) -[{t[1]}]-> ({t[2]})")

트리플 수: 1491
노드 수: 412, 엣지 수: 1491
관계 종류: ['AFFECTED_BY', 'CONTAINS', 'CONTROLS', 'HAS_FISH_TOXICITY', 'HAS_FORMULATION', 'HAS_PHI', 'HAS_TOXICITY', 'HAS_USE', 'MANUFACTURED_BY', 'USED_ON']

트리플 예시:
  (경탄) -[USED_ON]-> (고추(단고추류 포함))
  (경탄) -[CONTROLS]-> (역병)
  (경탄) -[CONTAINS]-> (Chlorothalonil+Kresoxim-methyl)
  (경탄) -[MANUFACTURED_BY]-> ((주)농협케미컬)
  (경탄) -[HAS_TOXICITY]-> (Ⅳ급(저독성))
  (경탄) -[HAS_FISH_TOXICITY]-> (Ⅰ급)
  (경탄) -[HAS_USE]-> (살균)
  (경탄) -[HAS_PHI]-> (수확3일전)

In [10]:
def find_seed_entities(question: str, g: nx.MultiDiGraph) -> List[str]:
    '''질문 문자열에 노드명이 부분 문자열로 포함되면 시작 개체로 채택한다. (01번 예제와 동일)'''
    # 실전에서는 NER을 쓰지만, 여기서는 노드명이 질문에 그대로 나오는지로 단순화한다.
    # 긴 이름을 앞에 두면 '고추(단고추류 포함)'이 '고추'보다 우선 매칭된다.
    seeds = [node for node in g.nodes() if node and str(node) in question]
    seeds.sort(key=len, reverse=True)
    return seeds


def k_hop_edges(g: nx.MultiDiGraph, seeds: List[str], k: int = 2) -> List[tuple]:
    '''seed로부터 양방향으로 최대 k홉까지 순회하며 지나온 엣지를 수집한다.'''
    visited_nodes = set(seeds)
    frontier = set(seeds)
    collected_edges = set()

    for _ in range(k):
        # 이번 홉에서 새로 도달한 노드만 다음에 확장한다. 이미 방문한 노드는 다시 넣지 않는다.
        next_frontier = set()
        for node in frontier:
            # 나가는 엣지: 제품 -[CONTROLS]-> 병해충
            for _, neighbor, data in g.out_edges(node, data=True):
                collected_edges.add((node, data["relation"], neighbor))
                if neighbor not in visited_nodes:
                    next_frontier.add(neighbor)
            # 들어오는 엣지: 회사 <-[MANUFACTURED_BY]- 제품 (역방향으로도 따라간다)
            for neighbor, _, data in g.in_edges(node, data=True):
                collected_edges.add((neighbor, data["relation"], node))
                if neighbor not in visited_nodes:
                    next_frontier.add(neighbor)
        visited_nodes |= next_frontier
        frontier = next_frontier
        if not frontier:
            break
    return sorted(collected_edges)


# 수집한 엣지를 LLM이 읽기 쉬운 '주체 -[관계]-> 객체' 텍스트로 바꾼다.
def edges_to_context(edges: List[tuple]) -> str:
    return "\n".join(f"- ({s}) -[{r}]-> ({o})" for s, r, o in edges)


def prioritize_edges(edges: List[tuple], seeds: List[str], limit: int = MAX_GRAPH_EDGES) -> List[tuple]:
    '''여러 seed와 동시에 연결된 엣지를 앞에 둔다. (작물+병해충 교집합 제품이 위로)'''
    seed_set = set(seeds)

    def score(e):
        s, r, o = e
        # seed가 주체이거나 객체이면 +1. 작물·병해충 양쪽에 걸린 엣지가 가장 높다.
        return int(s in seed_set) + int(o in seed_set)

    ranked = sorted(edges, key=score, reverse=True)
    return ranked[:limit]


# 질문 → seed 인식 → k홉 순회 → 길이 제한 → 텍스트 컨텍스트.
def graph_retrieve(question: str, g: nx.MultiDiGraph, k: int = GRAPH_HOPS) -> dict:
    seeds = find_seed_entities(question, g)
    edges = k_hop_edges(g, seeds, k=k) if seeds else []
    edges = prioritize_edges(edges, seeds)
    return {"seeds": seeds, "edges": edges, "context": edges_to_context(edges)}

### [2-1] Naive Vector RAG vs Graph RAG

In [11]:
# 질문을 그대로 임베딩해 제품 사실 문장 top-k를 가져온 뒤 grounded 답변을 만든다.
def naive_rag(question: str, k: int = TOP_N) -> dict:
    retrieved = product_vs.similarity_search(question, k=k)
    answer = answer_chain.invoke({"context": format_docs(retrieved), "question": question})
    return {"retrieved": retrieved, "answer": answer}


graph_answer_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "아래 [관계] 목록은 농약 지식 그래프에서 질문과 관련해 순회로 수집한 사실이다. "
            "이 관계들을 연결해 질문에 답하라. 목록만으로 답할 수 없으면 "
            "'주어진 자료만으로는 알 수 없다'라고 답하라.\n\n[관계]\n{context}",
        ),
        ("human", "{question}"),
    ]
)
graph_answer_chain = graph_answer_prompt | llm | StrOutputParser()


# 서브그래프 텍스트를 근거로 답을 생성한다. 검색 단위가 문장이 아니라 관계 트리플이다.
def graph_rag(question: str, g: nx.MultiDiGraph = graph, k: int = GRAPH_HOPS) -> dict:
    retrieval = graph_retrieve(question, g, k=k)
    answer = graph_answer_chain.invoke({"context": retrieval["context"], "question": question})
    return {**retrieval, "answer": answer}


# 샘플 상표는 방금 뽑은 데이터에서 가져와, 없는 제품명으로 질문하지 않게 한다.
sample_brand = str(products["상표명"].iloc[0])
sample_crop = str(products["작물명"].iloc[0])
sample_pest = str(products["적용병해충"].iloc[0])

query_fact = f"상표명 {sample_brand}의 주성분과 회사는?"
query_multi = "고추 탄저병에 사용할 수 있는 저독성 제품의 회사와 안전사용시기는?"
query_multi2 = "벼에 쓰는 살충제를 만드는 회사는 어디인가?"

print(f"[샘플 상표] {sample_brand} / {sample_crop} / {sample_pest}\n")

for q in [query_fact, query_multi, query_multi2]:
    t1 = time.time()
    naive = naive_rag(q)
    t_naive = time.time() - t1
    t1 = time.time()
    g_rag = graph_rag(q)
    t_graph = time.time() - t1
    print(f"질문: {q}")
    print(f"  Graph seed: {g_rag['seeds'][:8]} ... (edges={len(g_rag['edges'])})")
    print(f"  - Naive Vector RAG ({t_naive:.1f}s): {naive['answer'][:240]}")
    print(f"  - Graph RAG        ({t_graph:.1f}s): {g_rag['answer'][:240]}")
    print("-" * 80)

[샘플 상표] 경탄 / 고추(단고추류 포함) / 역병

질문: 상표명 경탄의 주성분과 회사는?
  Graph seed: ['경탄'] ... (edges=80)
  - Naive Vector RAG (1.5s): 상표명 '경탄'의 주성분은 Chlorothalonil+Kresoxim-methyl(함량 42(35+7)%)이며, 회사는 (주)농협케미컬입니다.
근거 유형: 제품목록
  - Graph RAG        (1.2s): 상표명 경탄의 주성분은 Chlorothalonil과 Kresoxim-methyl이며, 제조사는 (주)농협케미컬입니다.
--------------------------------------------------------------------------------
질문: 고추 탄저병에 사용할 수 있는 저독성 제품의 회사와 안전사용시기는?
  Graph seed: ['탄저병', '고추'] ... (edges=80)
  - Naive Vector RAG (2.1s): 고추 탄저병에 사용할 수 있는 저독성 제품은 다음과 같습니다:

1. '코어탄' - 회사: 빅스타네이처사이언스(주), 안전사용시기: 수확2일전
2. '르네상스' - 회사: (주)한얼싸이언스, 안전사용시기: 수확3일전
3. '머니업' - 회사: 아그리젠토(주), 안전사용시기: 수확3일전
4. '경탄' - 회사: (주)농협케미컬, 안전사용시기: 수확3일전

모든 제품의 인축독성은 Ⅳ급(저독성)입니다.

근거 유형: 제품목록
  - Graph RAG        (1.5s): 고추 탄저병에 사용할 수 있는 저독성 제품은 '경탄'입니다. 이 제품은 (주)농협케미컬에서 제조되며, 안전 사용 시기는 수확 3일 전입니다.
--------------------------------------------------------------------------------
질문: 벼에 쓰는 살충제를 만드는 회사는 어디인가?
  Graph seed: ['살충', '벼'] ... (edges=80)
  - Naive Vector RAG (0.9s): 주어진 자료만으로는 알 수 없다.
(근거 유형: 제품목록)
  - Graph RAG        (0.9s): 주어진 자료만으로는 알 수 없다.
--------------------------------------------------------------------------------

멀티홉 질문(작물 → 제품 → 독성/회사/안전사용시기)은 벡터 top-k에 연결 고리가 빠지면 답을 못 만든다.  
Graph RAG는 seed에서 관계를 따라가므로 같은 근거를 빠뜨리지 않는다. 반대로 상표명 주성분 같은 단일 사실은 두 방식 모두 잘 맞는다.

## 3. Agentic RAG — 검색 전략 자율 결정

벡터 검색·그래프 순회·안전사용 웹 검색을 도구로 주고, 어떤 도구를 몇 번 쓸지를 Agent가 판단한다.  
02번 예제와 같이 LangGraph ReAct 루프(`agent` ⇄ `tools`)를 사용한다.

In [12]:
# 세 검색 경로를 도구로 노출한다. Agent는 질문 유형에 따라 어떤 도구를 몇 번 쓸지 스스로 고른다.
from langchain_core.tools import tool
from langchain_core.messages import AnyMessage, HumanMessage, SystemMessage
from langgraph.graph import StateGraph, END
from langgraph.graph.message import add_messages
from langgraph.prebuilt import ToolNode


@tool
def vector_search(query: str) -> str:
    '''농약제품 사실 문장을 의미 유사도로 검색한다.
    "OO 상표의 주성분은?", "이 약의 회사는?"처럼 단일 사실 조회에 적합하다.
    정확한 상표명·작물명을 모를 때 실마리를 찾는 용도로도 쓸 수 있다.'''
    # 도구 docstring이 Agent의 선택 기준이므로, 언제 이 도구를 쓸지를 본문에 분명히 적는다.
    retrieved = product_vs.similarity_search(query, k=TOP_N)
    return format_docs(retrieved) if retrieved else "검색 결과 없음"


@tool
def graph_search(entity: str, hops: int = 2) -> str:
    '''지식 그래프에서 entity(상표명·작물명·병해충·회사명 등)를 시작점으로 최대 hops단계까지 관계를 순회한다.
    "고추 탄저병에 쓰는 약의 회사는?"처럼 여러 단계를 연결해야 하는 멀티홉 질문에 적합하다.
    entity는 그래프 노드명과 일치(또는 부분 일치)해야 하며, 못 찾으면 vector_search로 정확한 이름을 먼저 확인한다.'''
    seeds = [node for node in graph.nodes() if entity in str(node) or str(node) in entity]
    if not seeds:
        # 못 찾았다는 문구를 그대로 돌려줘야 Agent가 다음 도구(vector_search)로 전환한다.
        return f"'{entity}'와 일치하는 개체를 그래프에서 찾지 못함. 정확한 개체명 확인이 필요하다."
    edges = prioritize_edges(k_hop_edges(graph, seeds, k=hops), seeds)
    return edges_to_context(edges) if edges else f"'{entity}'에서 시작하는 관계를 찾지 못함"


@tool
def safety_search(query: str) -> str:
    '''농약 정의, 중독 증상, 응급처치, 사용 시 주의사항, 사용 후 관리 등 안전사용 웹 문서를 검색한다.
    제품 추천이 아니라 안전·응급 관련 질문에 사용한다.'''
    retrieved = web_vs.similarity_search(query, k=TOP_N)
    return format_docs(retrieved) if retrieved else "검색 결과 없음"


tools = [vector_search, graph_search, safety_search]

In [13]:
class AgentState(TypedDict):
    # add_messages: 새 메시지는 덮어쓰지 않고 대화 끝에 이어 붙인다.
    messages: Annotated[List[AnyMessage], add_messages]


SYSTEM_PROMPT = """당신은 농약 안전사용 상담 어시스턴트다. 다음 검색 도구를 자유롭게 사용할 수 있다.

- vector_search: 제품 사실 문장 의미 검색. 단일 사실 조회, 정확한 상표명을 모를 때 실마리 찾기에 적합.
- graph_search: 개체명 기점 그래프 순회. 작물-병해충-제품-회사-독성을 여러 단계로 연결할 때 적합.
- safety_search: 농약 정의·중독·응급처치·주의사항·사용 후 관리 웹 문서 검색.

지침:
1. 검색 없이 답할 수 있는 질문(인사, 역할 소개)은 도구를 호출하지 말고 바로 답하라.
2. 어떤 도구가 적합한지, 몇 번 호출할지는 스스로 판단하라.
3. graph_search가 개체를 찾지 못하면 vector_search로 정확한 이름을 파악한 뒤 다시 graph_search를 시도하라.
4. 제품 선택과 안전 수칙이 함께 필요하면 도구를 조합하라.
5. 충분한 근거를 모았으면 검색을 멈추고 근거에만 기반해 답하라. 부족하면 모른다고 답하라.
6. 최종 답변에 근거 유형을 간단히 함께 제시하라."""

llm_with_tools = llm.bind_tools(tools)


# 지금까지의 대화(질문+도구 결과)를 보고 도구를 더 쓸지, 바로 답할지 결정한다.
def agent_node(state: AgentState) -> dict:
    messages = state["messages"]
    if not any(isinstance(m, SystemMessage) for m in messages):
        messages = [SystemMessage(content=SYSTEM_PROMPT)] + messages
    response = llm_with_tools.invoke(messages)
    return {"messages": [response]}


# 마지막 AI 메시지에 tool_calls가 있으면 도구 노드로, 없으면 종료한다.
def should_continue(state: AgentState) -> str:
    last_message = state["messages"][-1]
    if getattr(last_message, "tool_calls", None):
        return "tools"
    return END


# ReAct 루프: agent → (도구가 필요하면) tools → agent → ... → 종료
workflow = StateGraph(AgentState)
workflow.add_node("agent", agent_node)
workflow.add_node("tools", ToolNode(tools))
workflow.set_entry_point("agent")
workflow.add_conditional_edges("agent", should_continue, {"tools": "tools", END: END})
workflow.add_edge("tools", "agent")
agentic_rag = workflow.compile()
print(agentic_rag.get_graph().draw_mermaid())

---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	agent(agent)
	tools(tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> agent;
	agent -.-> __end__;
	agent -.-> tools;
	tools --> agent;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

In [14]:
# Agent를 실행한 뒤 도구 호출 순서를 그대로 출력한다. recursion_limit으로 무한 루프를 막는다.
def run_agentic_rag(question: str, verbose: bool = True) -> str:
    result = agentic_rag.invoke(
        {"messages": [HumanMessage(content=question)]},
        config={"recursion_limit": 15},
    )
    messages = result["messages"]
    if verbose:
        print(f"질문: {question}\n")
        step = 1
        for m in messages[1:]:
            if getattr(m, "tool_calls", None):
                for call in m.tool_calls:
                    print(f"[{step}] Agent 판단 → 도구 호출: {call['name']}({call['args']})")
                    step += 1
            elif m.type == "tool":
                preview = m.content if len(m.content) < 280 else m.content[:280] + " ..."
                print(f"    └─ 도구 결과:\n{preview}\n")
            elif m.type == "ai" and m.content:
                print(f"[{step}] Agent 최종 답변:\n{m.content}")
    return messages[-1].content


# 인사(검색 불필요) / 단일 사실 / 멀티홉 / 안전 웹문서 네 유형을 확인한다.
agent_questions = [
    "안녕? 너는 무슨 일을 도와줄 수 있어?",
    query_fact,
    query_multi,
    "농약 중독 증상이 나타나면 어떻게 응급처치해야 하나요?",
]

agent_answers = {}
for q in agent_questions:
    t0 = time.time()
    ans = run_agentic_rag(q)
    agent_answers[q] = (ans, time.time() - t0)
    print("\n" + "=" * 80 + "\n")

질문: 안녕? 너는 무슨 일을 도와줄 수 있어?

[1] Agent 최종 답변:
안녕하세요! 저는 농약 안전사용에 관한 상담을 도와드릴 수 있습니다. 농약의 정의, 중독 증상, 응급처치 방법, 사용 시 주의사항, 그리고 사용 후 관리에 대한 정보 등을 제공할 수 있습니다. 궁금한 점이 있으면 말씀해 주세요!

================================================================================

질문: 상표명 경탄의 주성분과 회사는?

[1] Agent 판단 → 도구 호출: vector_search({'query': '경탄 주성분'})
[2] Agent 판단 → 도구 호출: vector_search({'query': '경탄 회사'})
    └─ 도구 결과:
- 상표명 '광충탄'는 작물 '고추'의 '열대거세미나방'에 사용하는 살충제이다. 품목명은 인독사카브 입상수화제이다. 주성분(일반명)은 Indoxacarb(함량 30%)이다. 인축독성은 Ⅳ급(저독성)이다. 어독성은 Ⅱ급이다. 회사는 선문그린사이언스(주)이다. 안전사용시기는 수확5일전이다. 안전사용횟수는 3회이다. 사용방법은 경엽처리이다. 사용적기는 발생 초부터이다. 제형은 입상수화제이다. 희석배수는 6000배이다.
- 상표명 '우승탄'는 작물 '배추'의 '무름병'에 사용하는 살균제이다. 품목명은 옥 ...

    └─ 도구 결과:
- 상표명 '경탄'는 작물 '고추(단고추류 포함)'의 '탄저병'에 사용하는 살균제이다. 품목명은 클로로탈로닐.크레속심메틸 액상수화제이다. 주성분(일반명)은 Chlorothalonil+Kresoxim-methyl(함량 42(35+7)%)이다. 인축독성은 Ⅳ급(저독성)이다. 어독성은 Ⅰ급이다. 회사는 (주)농협케미컬이다. 안전사용시기는 수확3일전이다. 안전사용횟수는 3회이다. 사용방법은 경엽처리이다. 사용적기는 발병 초부터이다. 제형은 액상수화제이다. 희석배수는 1000배이다.
- 상표명 '경탄'는  ...

[3] Agent 최종 답변:
상표명 "경탄"의 주성분은 Chlorothalonil과 Kresoxim-methyl의 혼합물로, 함량은 42% (35% + 7%)입니다. 이 제품은 (주)농협케미컬에서 제조합니다.

근거 유형: 제품 사실 조회 결과.

================================================================================

질문: 고추 탄저병에 사용할 수 있는 저독성 제품의 회사와 안전사용시기는?

[1] Agent 판단 → 도구 호출: graph_search({'entity': '고추 탄저병', 'hops': 2})
[2] Agent 판단 → 도구 호출: safety_search({'query': '고추 탄저병 저독성 농약 안전사용시기'})
    └─ 도구 결과:
- (고추) -[AFFECTED_BY]-> (탄저병)
- (경탄) -[CONTROLS]-> (탄저병)
- (고추) -[AFFECTED_BY]-> (갈색점무늬병)
- (고추) -[AFFECTED_BY]-> (과실파리류)
- (고추) -[AFFECTED_BY]-> (꽃노랑총채벌레)
- (고추) -[AFFECTED_BY]-> (담배나방)
- (고추) -[AFFECTED_BY]-> (매미나방)
- (고추) -[AFFECTED_BY]-> (목화진딧물)
- (고추) -[AFFECTED_BY]-> (복숭아혹진 ...

    └─ 도구 결과:
- 농약 중독의 증상 < 농약안전사용 < 안전사용정보 | 농촌진흥청 농약안전정보시스템
본문 바로가기
주메뉴 바로가기
사이드메뉴 바로가기
이 누리집은 대한민국 공식 전자정부 누리집입니다.
화면크기
작게
보통
조금 크게
크게
가장크게
초기화
농촌진흥청 농약안전정보시스템
로그인
회원가입
농촌진흥청 농약안전정보시스템
농약판매기록
농약판매기록안내
농약판매기록절차
민원서비스
민원서비스안내
민원서비스신청절차
농약평가절차
평가개요 및 절차
이화학성 평가
생물활성 평가
인축독성 평가
환경생물독성 평가
ADI·AO ...

[3] Agent 최종 답변:
고추 탄저병에 사용할 수 있는 저독성 제품으로는 "경탄"과 "광충탄"이 있습니다. 이 두 제품은 각각 다음과 같은 정보를 가지고 있습니다:

1. **경탄**
   - 제조사: 농협케미컬
   - 독성 등급: Ⅳ급 (저독성)
   - 사용 용도: 살균
   - 수확 전 대기 기간: 3일

2. **광충탄**
   - 제조사: 선문그린사이언스(주)
   - 독성 등급: Ⅳ급 (저독성)
   - 사용 용도: 살충
   - 수확 전 대기 기간: 5일

안전 사용 시기는 각 제품의 수확 전 대기 기간에 따라 다르며, 경탄은 수확 3일 전, 광충탄은 수확 5일 전까지 사용해야 합니다.

**근거 유형**: 제품 정보는 그래프 검색을 통해 확인하였고, 안전 사용 시기는 농약 안전 사용 관련 웹 문서에서 확인하였습니다.

================================================================================

질문: 농약 중독 증상이 나타나면 어떻게 응급처치해야 하나요?

[1] Agent 판단 → 도구 호출: safety_search({'query': '농약 중독 응급처치'})
    └─ 도구 결과:
- 질문농약에 중독되었을 경우 어떻게 해야 하는가? 답변농약에 중독되었을 경우 어떻게 해야 하는가?
농약의 중독증상
농약의 중독증상은 농약의 종류에 따라 다르나 신경계에 영향을 미치고, 일부 농약은 피부와 안점막자극을 일으킵니다.
유기인계 및 카바메이트계 농약은 피부에 묻으면 쉽게 흡수되며 두통, 현기증, 설사, 발한 등을 유발합니다.
유기염소계 농약은 장기적으로 지방에 축적되어 중독을 나타내고, 내분비계 의심 물질로 되어 사용이 거의 금지된 상태입니다.
패러쾃액제(그라목손)는 위 점막, 간, 콩 ...

[2] Agent 최종 답변:
농약 중독이 발생했을 경우, 다음과 같은 응급처치를 취해야 합니다:

1. **농약 종류 확인**: 중독된 농약의 종류를 파악하는 것이 중요합니다. 이를 통해 적절한 응급처치를 할 수 있습니다.

2. **의식 상태 확인**: 중독된 사람이 의식이 없거나 호흡곤란, 경련을 겪는 경우에는 즉시 응급처치를 시행하고, 의료기관에 연락하여 도움을 요청해야 합니다.

3. **의식이 있는 경우**: 중독된 사람이 의식이 있을 때는 해당 농약의 라벨을 참조하여 응급처치를 진행합니다.

4. **피부에 묻었을 경우**: 농약이 피부에 묻었다면, 흐르는 물로 씻어낸 후 비눗물로 완전히 씻어야 합니다.

이러한 응급처치는 농약의 종류와 중독 증상에 따라 달라질 수 있으므로, 가능한 한 빨리 전문가의 도움을 받는 것이 중요합니다.

**근거 유형**: 농약 중독 증상 및 응급처치 방법에 대한 안전사용 정보.

================================================================================

## 4. Self-Corrective RAG — 검색 결과 자기평가·재시도

03번 예제의 CRAG 흐름을 농약 도메인에 옮긴다.

1. 제품 KB(내부)를 벡터 검색한다.
2. LLM이 문서마다 관련 여부를 `yes`/`no`로 채점한다.
3. 관련 문서가 없으면 질의를 재작성하고 다시 검색한다.
4. 재시도를 다 쓰면 안전사용 웹 문서(외부)로 전환한다.
5. 그래도 없으면 모른다고 답한다.

In [15]:
from pydantic import BaseModel, Field
import operator


class GradeDocument(BaseModel):
    # structured output으로 yes/no만 받아, 채점 결과를 파싱 없이 라우팅에 쓴다.
    binary_score: str = Field(description="문서가 질문에 답하는 데 관련이 있으면 'yes', 없으면 'no'")


grade_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "당신은 검색된 문서가 사용자 질문과 관련이 있는지 채점하는 채점자다.\n"
            "문서에 질문과 관련된 키워드나 의미가 담겨 있으면 관련 있다고 판단한다.\n"
            "엄격한 정답 일치가 아니라, 답을 찾는 데 실제로 도움이 되는지를 기준으로 느슨하게 채점하되,\n"
            "명백히 무관한 주제라면 'no'로 채점하라.",
        ),
        ("human", "[검색된 문서]\n{document}\n\n[질문]\n{question}"),
    ]
)
# 관련 없음 → 같은 질문으로 재검색해도 결과가 같으므로, 핵심어를 살린 질의로 바꿔야 한다.
grade_chain = grade_prompt | llm.with_structured_output(GradeDocument)

rewrite_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "다음 질문으로 검색했지만 관련 문서를 찾지 못했다. 검색에 더 적합하도록 질문을 다시 작성하라.\n"
            "- 원래 질문의 의도는 그대로 유지한다.\n"
            "- 구어체·오탈자·축약 지칭을 작물명·병해충명·상표명 등 핵심어로 풀어 쓴다.\n"
            "- 재작성한 질문 한 줄만 출력하고, 다른 설명은 덧붙이지 않는다.",
        ),
        ("human", "원래 질문: {question}"),
    ]
)
rewrite_chain = rewrite_prompt | llm | StrOutputParser()

generate_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "아래 [근거] 문서만 사용해 질문에 답하라. 문서에 없는 내용은 추측하지 마라.\n"
            "답변 끝에 근거 출처가 제품목록(내부)인지 안전사용 웹문서(외부)인지 한 줄로 밝혀라.",
        ),
        ("human", "[근거 출처: {source}]\n{context}\n\n[질문]\n{question}"),
    ]
)
generate_chain = generate_prompt | llm | StrOutputParser()

# 관련 문서와 무관 문서를 한 번씩 넣어 채점기가 yes/no를 구분하는지 확인한다.
# 채점기 단독 테스트
print(
    "관련 문서 채점:",
    grade_chain.invoke(
        {"document": product_docs[0].page_content, "question": query_fact}
    ).binary_score,
)
print(
    "무관 문서 채점:",
    grade_chain.invoke(
        {
            "document": "테크노바는 2016년에 설립된 IT 기업이다.",
            "question": "고추 탄저병 약 추천해줘",
        }
    ).binary_score,
)

관련 문서 채점: yes
무관 문서 채점: no

In [16]:
class CRAGState(TypedDict):
    # question: 현재 검색 질의(재작성되면 바뀜) / original_question: 사용자 원문(채점·생성 기준)
    question: str
    original_question: str
    documents: List[Document]
    retry_count: int
    used_web: bool
    generation: str
    # 노드마다 로그를 이어 붙여 검색→채점→재작성/웹전환 경로를 추적한다.
    trace: Annotated[List[str], operator.add]


# 내부 지식(제품 KB)만 검색한다. 웹 전환은 재시도를 다 쓴 뒤에만 한다.
def retrieve(state: CRAGState) -> dict:
    documents = product_vs.similarity_search(state["question"], k=TOP_N)
    return {
        "documents": documents,
        "trace": [f"[검색] 질의 '{state['question']}' → 제품 KB {len(documents)}건"],
    }


# 유사도가 높아도 질문과 무관한 문서는 버린다. 채점은 원본 질문 기준.
def grade_documents(state: CRAGState) -> dict:
    trace_lines = []
    relevant = []
    for d in state["documents"]:
        # 문서마다 LLM에 관련 여부를 물어 yes만 남긴다. 벡터 점수만으로는 오탐을 못 걸러낸다.
        score = grade_chain.invoke(
            {"document": d.page_content, "question": state["original_question"]}
        )
        flag = "관련" if score.binary_score.lower() == "yes" else "무관"
        preview = d.page_content[:80].replace("\n", " ")
        trace_lines.append(f"    · [{flag}] {preview}")
        if score.binary_score.lower() == "yes":
            relevant.append(d)
    trace_lines.insert(0, f"[채점] 검색된 {len(state['documents'])}건 중 관련 문서 {len(relevant)}건")
    return {"documents": relevant, "trace": trace_lines}


# 구어체·오탈자를 작물명·병해충명 같은 핵심어로 풀어 재검색한다.
def transform_query(state: CRAGState) -> dict:
    rewritten = rewrite_chain.invoke({"question": state["question"]})
    return {
        "question": rewritten,
        "retry_count": state["retry_count"] + 1,
        "trace": [f"[재작성] '{state['question']}' → '{rewritten}' (시도 {state['retry_count'] + 1}/{MAX_CRAG_RETRIES})"],
    }


# 제품 KB에 없는 정의·응급처치 질문은 안전사용 웹 청크로 넘긴다.
def web_search(state: CRAGState) -> dict:
    documents = web_vs.similarity_search(state["original_question"], k=TOP_N)
    return {
        "documents": documents,
        "used_web": True,
        "trace": [f"[웹전환] 안전사용 웹문서에서 {len(documents)}건"],
    }


# 근거가 전혀 없으면 모른다고 답하고, 있으면 출처(내부/외부)를 명시해 생성한다.
def generate(state: CRAGState) -> dict:
    source = "안전사용 웹문서(외부)" if state.get("used_web") else "제품목록(내부)"
    if not state["documents"]:
        generation = "주어진 자료만으로는 알 수 없다.\n근거 출처: 없음"
        trace = ["[생성] 관련 근거 없음 → 모른다고 답변"]
    else:
        generation = generate_chain.invoke(
            {
                "source": source,
                "context": format_docs(state["documents"]),
                "question": state["original_question"],
            }
        )
        trace = [f"[생성] {source} {len(state['documents'])}건을 근거로 최종 답변 작성"]
    return {"generation": generation, "trace": trace}


# 관련 문서 있음 → 생성 / 재시도 남음 → 질의 재작성 / 소진 → 웹 검색
def route_after_grade(state: CRAGState) -> str:
    if state["documents"]:
        return "generate"
    if state["retry_count"] < MAX_CRAG_RETRIES:
        return "transform_query"
    return "web_search"


crag = StateGraph(CRAGState)
crag.add_node("retrieve", retrieve)
crag.add_node("grade_documents", grade_documents)
crag.add_node("transform_query", transform_query)
crag.add_node("web_search", web_search)
crag.add_node("generate", generate)
crag.set_entry_point("retrieve")
crag.add_edge("retrieve", "grade_documents")
crag.add_conditional_edges(
    "grade_documents",
    route_after_grade,
    {"generate": "generate", "transform_query": "transform_query", "web_search": "web_search"},
)
crag.add_edge("transform_query", "retrieve")
crag.add_edge("web_search", "generate")
crag.add_edge("generate", END)
self_corrective_rag = crag.compile()
print(self_corrective_rag.get_graph().draw_mermaid())

---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	retrieve(retrieve)
	grade_documents(grade_documents)
	transform_query(transform_query)
	web_search(web_search)
	generate(generate)
	__end__([<p>__end__</p>]):::last
	__start__ --> retrieve;
	grade_documents -.-> generate;
	grade_documents -.-> transform_query;
	grade_documents -.-> web_search;
	retrieve --> grade_documents;
	transform_query --> retrieve;
	web_search --> generate;
	generate --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

In [17]:
# CRAG 그래프를 돌리고 검색→채점→재작성/웹전환 경로를 한 줄씩 출력한다.
def run_self_corrective_rag(question: str, verbose: bool = True) -> str:
    init_state: CRAGState = {
        "question": question,
        "original_question": question,
        "documents": [],
        "retry_count": 0,
        "used_web": False,
        "generation": "",
        "trace": [],
    }
    result = self_corrective_rag.invoke(init_state, config={"recursion_limit": 15})
    if verbose:
        print(f"질문: {question}\n")
        for line in result["trace"]:
            print(line)
        print(f"\n최종 답변:\n{result['generation']}")
    return result["generation"]


# 정상 제품 질문 / 구어체·오탈자 / 제품 KB에 없는 정의 / 사용 후 관리(웹)
crag_questions = [
    query_fact,
    "고충에 탄저 올때 저독성으로 뭐 뿌림? 어느 회사꺼야?",
    "농약이란 무엇이며 신농약이 등록되기까지 왜 어려운가요?",
    "농약 사용 후 빈 용기는 어떻게 관리해야 하나요?",
]

crag_answers = {}
for q in crag_questions:
    t0 = time.time()
    ans = run_self_corrective_rag(q)
    crag_answers[q] = (ans, time.time() - t0)
    print("\n" + "=" * 80 + "\n")

질문: 상표명 경탄의 주성분과 회사는?

[검색] 질의 '상표명 경탄의 주성분과 회사는?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 2건
    · [관련] 상표명 '경탄'는 작물 '고추(단고추류 포함)'의 '갈색점무늬병'에 사용하는 살균제이다. 품목명은 클로로탈로닐.크레속심메틸 액상수화제이다. 주성
    · [무관] 상표명 '광충탄'는 작물 '고추'의 '열대거세미나방'에 사용하는 살충제이다. 품목명은 인독사카브 입상수화제이다. 주성분(일반명)은 Indoxac
    · [무관] 상표명 '광충탄'는 작물 '고추'의 '과실파리류'에 사용하는 살충제이다. 품목명은 인독사카브 입상수화제이다. 주성분(일반명)은 Indoxacar
    · [관련] 상표명 '경탄'는 작물 '고추(단고추류 포함)'의 '역병'에 사용하는 살균제이다. 품목명은 클로로탈로닐.크레속심메틸 액상수화제이다. 주성분(일반
[생성] 제품목록(내부) 2건을 근거로 최종 답변 작성

최종 답변:
상표명 '경탄'의 주성분은 Chlorothalonil+Kresoxim-methyl(함량 42(35+7)%)이며, 회사는 (주)농협케미컬입니다.

근거 출처: 제품목록(내부)

================================================================================

질문: 고충에 탄저 올때 저독성으로 뭐 뿌림? 어느 회사꺼야?

[검색] 질의 '고충에 탄저 올때 저독성으로 뭐 뿌림? 어느 회사꺼야?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 4건
    · [관련] 상표명 '코어탄'는 작물 '고추'의 '탄저병'에 사용하는 살균제이다. 품목명은 테부코나졸 유제이다. 주성분(일반명)은 Tebuconazole(함
    · [관련] 상표명 '광충탄'는 작물 '고추'의 '담배나방'에 사용하는 살충제이다. 품목명은 인독사카브 입상수화제이다. 주성분(일반명)은 Indoxacarb
    · [관련] 상표명 '요절충'는 작물 '고추'의 '과실파리류'에 사용하는 살충제이다. 품목명은 에토펜프록스 유제이다. 주성분(일반명)은 Etofenprox(
    · [관련] 상표명 '광충탄'는 작물 '고추'의 '과실파리류'에 사용하는 살충제이다. 품목명은 인독사카브 입상수화제이다. 주성분(일반명)은 Indoxacar
[생성] 제품목록(내부) 4건을 근거로 최종 답변 작성

최종 답변:
고추의 탄저병에 사용할 수 있는 저독성 살균제는 '코어탄'입니다. 이 제품은 빅스타네이처사이언스(주)에서 제조합니다.

근거 출처: 제품목록(내부)

================================================================================

질문: 농약이란 무엇이며 신농약이 등록되기까지 왜 어려운가요?

[검색] 질의 '농약이란 무엇이며 신농약이 등록되기까지 왜 어려운가요?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 0건
    · [무관] 상표명 '실루엣'는 작물 '벼'의 '전착효과'에 사용하는 기타제이다. 품목명은 실록세인 액제이다. 주성분(일반명)은 Siloxane(함량 30%
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '흰잎마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
[재작성] '농약이란 무엇이며 신농약이 등록되기까지 왜 어려운가요?' → '농약의 정의와 신농약 등록 과정의 어려움은 무엇인가요?' (시도 1/2)
[검색] 질의 '농약의 정의와 신농약 등록 과정의 어려움은 무엇인가요?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 0건
    · [무관] 상표명 '실루엣'는 작물 '벼'의 '전착효과'에 사용하는 기타제이다. 품목명은 실록세인 액제이다. 주성분(일반명)은 Siloxane(함량 30%
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '흰잎마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
[재작성] '농약의 정의와 신농약 등록 과정의 어려움은 무엇인가요?' → '농약의 정의와 신농약 등록 과정에서의 어려움은 무엇인가요?' (시도 2/2)
[검색] 질의 '농약의 정의와 신농약 등록 과정에서의 어려움은 무엇인가요?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 0건
    · [무관] 상표명 '실루엣'는 작물 '벼'의 '전착효과'에 사용하는 기타제이다. 품목명은 실록세인 액제이다. 주성분(일반명)은 Siloxane(함량 30%
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '흰잎마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
[웹전환] 안전사용 웹문서에서 4건
[생성] 안전사용 웹문서(외부) 4건을 근거로 최종 답변 작성

최종 답변:
농약이란 농작물을 재배하기 위한 농경지의 토양소독, 종자 소독, 병해충으로부터 농작물을 보호하고, 수확한 농산물의 저장 시 병해충에 의한 손실을 방지하기 위해 사용되는 모든 약제를 포함합니다. 또한 농작물의 생육을 촉진하거나 억제하는 약제, 품질을 향상시키는 약제도 농약으로 규정됩니다.

신농약이 등록되기까지 어려운 이유는, 후보화합물이 농약으로 등록되기 위해서는 효과시험, 독성시험 등 많은 시험을 수행하여 효과와 안전성을 확인해야 하며, 등록되는 비율이 35,000 : 1로 매우 낮기 때문입니다. 또한, 화합물의 합성부터 등록까지는 10년 이상의 시간과 1,500억원 이상의 연구개발비가 소요되며, 최종적으로 시험동물을 이용하여 안전성을 확인해야 합니다. 이러한 과정들이 신농약의 등록을 어렵게 만듭니다.

근거 출처: 안전사용 웹문서(외부)

================================================================================

질문: 농약 사용 후 빈 용기는 어떻게 관리해야 하나요?

[검색] 질의 '농약 사용 후 빈 용기는 어떻게 관리해야 하나요?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 0건
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명
    · [무관] 상표명 '유원발리'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 발리다마이신에이 액제이다. 주성분(일반명)은 Validam
[재작성] '농약 사용 후 빈 용기는 어떻게 관리해야 하나요?' → '농약 사용 후 빈 용기를 어떻게 관리해야 하나요?' (시도 1/2)
[검색] 질의 '농약 사용 후 빈 용기를 어떻게 관리해야 하나요?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 0건
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명
    · [무관] 상표명 '유원발리'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 발리다마이신에이 액제이다. 주성분(일반명)은 Validam
[재작성] '농약 사용 후 빈 용기를 어떻게 관리해야 하나요?' → '농약 사용 후 빈 용기를 어떻게 관리해야 하나요?' (시도 2/2)
[검색] 질의 '농약 사용 후 빈 용기를 어떻게 관리해야 하나요?' → 제품 KB 4건
[채점] 검색된 4건 중 관련 문서 0건
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '목도열병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명)은
    · [무관] 상표명 '농부마음'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 아족시스트로빈.플룩사피록사드 액상수화제이다. 주성분(일반명
    · [무관] 상표명 '유원발리'는 작물 '벼'의 '잎집무늬마름병'에 사용하는 살균제이다. 품목명은 발리다마이신에이 액제이다. 주성분(일반명)은 Validam
[웹전환] 안전사용 웹문서에서 4건
[생성] 안전사용 웹문서(외부) 4건을 근거로 최종 답변 작성

최종 답변:
농약 사용 후 빈 용기는 한국환경공단에서 지정한 처리업체에서 처리해야 합니다. 빈 용기를 별도로 구분하여 안전하게 처리하는 것이 중요합니다.

근거 출처: 안전사용 웹문서(외부)

================================================================================

## 5. RAG Fusion — 앙상블 검색 통합

04번 예제와 같이, 최선의 질의 하나를 고르지 않고 **여러 질의 변형 + 여러 검색 방식**의 순위를 RRF로 합친다.

$$\text{score}(d) = \sum_{l \in \text{lists}} \frac{1}{k + \text{rank}_l(d)},\quad k=60$$

In [18]:
class QueryVariations(BaseModel):
    queries: List[str] = Field(description="원래 질문을 서로 다른 표현·관점으로 재작성한 검색 질의 목록")


multi_query_prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            "당신은 검색 질의를 다양화하는 도우미다. 아래 질문을 벡터 검색에 쓸 수 있도록 "
            "서로 다른 표현·핵심어·관점으로 재작성한 질의를 {n}개 만들어라.\n"
            "- 원래 질문의 의도는 유지하되, 동의어·상위 개념·세부 키워드 등 표현을 다양화한다.\n"
            "- 각 질의는 한 문장으로 작성하고, 질의끼리 서로 겹치지 않게 한다.",
        ),
        ("human", "{question}"),
    ]
)
multi_query_chain = multi_query_prompt | llm.with_structured_output(QueryVariations)


# 원본 질의 + 변형 n개. 표현이 달라도 같은 의도의 문서를 폭넓게 찾게 한다.
def generate_query_variations(question: str, n: int = 4) -> List[str]:
    variations = multi_query_chain.invoke({"question": question, "n": n}).queries
    return [question] + variations


# 질의마다 독립적으로 벡터 검색해 순위 리스트를 만든다. 같은 문서가 서로 다른 순위로 중복될 수 있다.
def retrieve_for_queries(queries: List[str], k: int = TOP_N) -> List[List[Document]]:
    return [combined_vs.similarity_search(q, k=k) for q in queries]


# 여러 순위 리스트를 유사도 점수가 아니라 순위만으로 합산한다.
# score(d) = Σ 1/(k + rank). k=60은 1위 문서가 과도하게 독점하지 않게 하는 감쇠 상수.
# 순위만 쓰므로 코사인 유사도와 BM25처럼 스케일이 다른 검색도 그대로 섞을 수 있다.
def reciprocal_rank_fusion(
    ranked_lists: List[List[Document]],
    k: int = 60,
    top_n: int = TOP_N,
) -> List[Tuple[Document, float]]:
    scores: Dict[str, float] = defaultdict(float)
    doc_by_key: Dict[str, Document] = {}
    for ranked_list in ranked_lists:
        for rank, doc in enumerate(ranked_list, start=1):
            key = doc.page_content
            # 같은 문서는 page_content로 합친다. 여러 질의에 반복 등장할수록 점수가 올라간다.
            scores[key] += 1.0 / (k + rank)
            doc_by_key.setdefault(key, doc)
    fused = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return [(doc_by_key[key], score) for key, score in fused[:top_n]]


def rag_fusion(question: str, n_variations: int = 4) -> dict:
    # 변형 질의로 각각 검색한 뒤 RRF로 한 순위표를 만들고, 그 상위 문서로만 답한다.
    variations = generate_query_variations(question, n=n_variations)
    ranked_lists = retrieve_for_queries(variations, k=TOP_N)
    fused = reciprocal_rank_fusion(ranked_lists, top_n=TOP_N)
    docs = [d for d, _ in fused]
    answer = answer_chain.invoke({"context": format_docs(docs), "question": question})
    return {"variations": variations, "fused": fused, "answer": answer}

In [19]:
# 한 질문에 수확 전 대기기간(제품 KB)과 중독 응급처치(웹 문서)가 함께 들어 있다.
# 단일 질의는 한쪽에 치우치기 쉽고, 질의 변형+RRF는 두 출처를 한 순위표로 모은다.
fusion_query = "배추나 고추에 약 치고 나서 수확 며칠 전까지 사용해야 하고, 중독되면 어떻게 응급처치하지?"
fusion_result = rag_fusion(fusion_query)

print("=== 생성된 질의 변형 ===")
for i, q in enumerate(fusion_result["variations"]):
    label = "원본" if i == 0 else f"변형 {i}"
    print(f"[{label}] {q}")

print("\n=== RRF 융합 상위 문서 ===")
for i, (doc, score) in enumerate(fusion_result["fused"], 1):
    src = doc.metadata.get("doc_type") or doc.metadata.get("title") or doc.metadata.get("source")
    print(f"{i}위 (score={score:.4f}, {src}) {doc.page_content[:90].replace(chr(10), ' ')}")

print("\n=== Fusion 답변 ===")
print(fusion_result["answer"])

print("\n=== Naive (통합 스토어, 단일 질의) ===")
naive_combined = combined_vs.similarity_search(fusion_query, k=TOP_N)
print(answer_chain.invoke({"context": format_docs(naive_combined), "question": fusion_query}))

=== 생성된 질의 변형 ===
[원본] 배추나 고추에 약 치고 나서 수확 며칠 전까지 사용해야 하고, 중독되면 어떻게 응급처치하지?
[변형 1] 배추나 고추에 농약을 사용한 후 수확하기 전까지의 안전한 사용 기간은 얼마인가요?
[변형 2] 고추와 배추에 살충제를 뿌린 후 수확 전까지의 사용 제한 기간은 어떻게 되나요?
[변형 3] 배추와 고추에 약제를 사용한 후 수확 전까지의 대기 기간과 중독 시 응급처치 방법은 무엇인가요?
[변형 4] 고추와 배추에 농약을 처리한 후 수확하기 전까지의 사용 지침과 중독 시 대처 방법은 어떤 것이 있나요?

=== RRF 융합 상위 문서 ===
1위 (score=0.0481, safety_web) 안전사용기준이 필요 없는 농약은 사람이 식용으로 하지 않는 잔디에 사용되는 약제나 미생물제, 무기농약 또는 수확물에 잔류가 되지 않는 농약 등이 있습니다. 농약
2위 (score=0.0328, safety_web) 체온 유지 환자의 의식이 없다면 환자의 체온을 조절하기 위한 조치를 취해야 합니다. 만약 환자가 극도로 열이 높거나 과도하게 침을 흘린다면 차가운 물을 묻힌 수건
3위 (score=0.0317, safety_web) 이화학적특성정보 작용특성정보 제품공정분석법 잔류농약분석법 독성노출정보 농약 작용기작정보 농약허용기준강화제도(PLS) 병해충방제정보 병해충도감정보 수출작목별지침 농
4위 (score=0.0315, product) 상표명 '다조미드'는 작물 '배추'의 '뿌리혹병'에 사용하는 살균제이다. 품목명은 다조멧 입제이다. 주성분(일반명)은 Dazomet(함량 96.5%)이다. 인축독

=== Fusion 답변 ===
주어진 자료만으로는 배추와 고추에 대한 농약 사용 시기와 횟수에 대한 정보는 확인할 수 없습니다. 또한, 농약 중독 시 응급처치에 대한 정보는 삼킨 농약이 고독성이 아니라면 구토를 유발하는 것은 바람직하지 않으며, 구토를 유도해야 하는 경우에는 농약의 라벨에 적혀있는 지침을 따라야 한다고만 나와 있습니다. 따라서 구체적인 응급처치 방법은 주어진 자료만으로는 알 수 없습니다.

근거 유형: 안전사용 웹문서

=== Naive (통합 스토어, 단일 질의) ===
배추나 고추에 사용되는 농약의 수확 전 사용 기준에 대한 정보는 주어진 자료에 포함되어 있지 않으므로, 주어진 자료만으로는 알 수 없습니다.

농약 중독 시 응급처치는 다음과 같습니다. 농약에 중독되었을 때는 신속하게 응급처치를 진행해야 하며, 당황하지 말고 침착하게 행동해야 합니다. 먼저 호흡 여부를 확인하고, 호흡이 멈추었다면 인공호흡을 진행해야 합니다. 만약 눈에 농약이 들어갔다면 깨끗한 물로 빠르게 씻어내야 합니다. 환자가 의식이 없거나 호흡이 멈출 수 있으므로, 환자의 호흡과 의식에 이상이 없는지 확인해야 하며, 환자를 안정된 상태로 유지해야 합니다.

근거 유형: 안전사용 웹문서

### [5-1] Hybrid Ensemble — Dense(벡터) + Sparse(BM25)

순위만 쓰는 RRF이므로 코사인 유사도와 BM25처럼 스케일이 다른 점수도 그대로 섞을 수 있다.

In [20]:
from langchain_community.retrievers import BM25Retriever

try:
    from langchain_classic.retrievers.ensemble import EnsembleRetriever
except Exception:
    from langchain.retrievers import EnsembleRetriever

# BM25는 질의에 등장한 단어가 문서에 그대로 있는지를 본다. 희석배수·상표명 같은 고유 표기에 강하다.
bm25_retriever = BM25Retriever.from_documents(product_docs + web_chunks)
bm25_retriever.k = TOP_N
dense_retriever = combined_vs.as_retriever(search_kwargs={"k": TOP_N})


# 벡터(의미)와 BM25(키워드) 순위 리스트를 RRF로 한 표로 합친다.
def hybrid_fuse(question: str, top_n: int = TOP_N) -> List[Document]:
    dense_docs = combined_vs.similarity_search(question, k=top_n)
    # 의미 검색과 키워드 검색을 같은 질문으로 나란히 실행한 뒤 순위만 합친다.
    sparse_docs = bm25_retriever.invoke(question)
    fused = reciprocal_rank_fusion([dense_docs, sparse_docs], top_n=top_n)
    return [d for d, _ in fused]


# LangChain 내장 EnsembleRetriever는 위에서 직접 구현한 RRF와 같은 패턴이다. weights로 기여도를 조절한다.
ensemble_retriever = EnsembleRetriever(
    retrievers=[dense_retriever, bm25_retriever],
    weights=[0.5, 0.5],
)

hybrid_q = query_multi
print("질문:", hybrid_q)
print("\n=== Dense(벡터) ===")
for d in combined_vs.similarity_search(hybrid_q, k=TOP_N):
    print("-", d.page_content[:90].replace("\n", " "))
print("\n=== BM25(sparse) ===")
for d in bm25_retriever.invoke(hybrid_q):
    print("-", d.page_content[:90].replace("\n", " "))
print("\n=== Hybrid RRF ===")
hybrid_docs = hybrid_fuse(hybrid_q)
for d in hybrid_docs:
    print("-", d.page_content[:90].replace("\n", " "))
print("\n=== EnsembleRetriever ===")
for d in ensemble_retriever.invoke(hybrid_q)[:TOP_N]:
    print("-", d.page_content[:90].replace("\n", " "))

hybrid_answer = answer_chain.invoke({"context": format_docs(hybrid_docs), "question": hybrid_q})
print("\n=== Hybrid 답변 ===")
print(hybrid_answer)

질문: 고추 탄저병에 사용할 수 있는 저독성 제품의 회사와 안전사용시기는?

=== Dense(벡터) ===
- 상표명 '코어탄'는 작물 '고추'의 '탄저병'에 사용하는 살균제이다. 품목명은 테부코나졸 유제이다. 주성분(일반명)은 Tebuconazole(함량 25%)이다.
- 상표명 '르네상스'는 작물 '고추(단고추류 포함)'의 '탄저병'에 사용하는 살균제이다. 품목명은 디페노코나졸.테부코나졸 분산성액제이다. 주성분(일반명)은 Dife
- 상표명 '머니업'는 작물 '고추(단고추류 포함)'의 '탄저병'에 사용하는 살균제이다. 품목명은 프로클로라즈망가니즈 수화제이다. 주성분(일반명)은 Prochlora
- 상표명 '경탄'는 작물 '고추(단고추류 포함)'의 '탄저병'에 사용하는 살균제이다. 품목명은 클로로탈로닐.크레속심메틸 액상수화제이다. 주성분(일반명)은 Chlor

=== BM25(sparse) ===
- 적절한 보호 장비 선택 마스크 마스크를 효과적으로 사용하려면 마스크와 피부 사이에 틈이 생기지 않도록 얼굴에 밀착시켜야 합니다. 또한 귀에만 거는 형태보다는 2줄
- 상표명 '실루엣'는 작물 '벼'의 '전착효과'에 사용하는 기타제이다. 품목명은 실록세인 액제이다. 주성분(일반명)은 Siloxane(함량 30%)이다. 인축독성은
- 또한 병해충 등으로 인하여 재배가 불가능하거나 수량 감소가 컸던 다수성 품종의 재배를 가능하게 한 것은 우수한 농약의 공급에 의한 것입니다. 농촌의 일손을 획기적
- 농약의 독성구분은 실제 농약을 사용하는 농업인의 안전을 위하여 필요한 것으로 제품농약의 독성으로 구분합니다. 농약의 독성구분 기준(단위 : 반수치사량, LD50)

=== Hybrid RRF ===
- 상표명 '코어탄'는 작물 '고추'의 '탄저병'에 사용하는 살균제이다. 품목명은 테부코나졸 유제이다. 주성분(일반명)은 Tebuconazole(함량 25%)이다.
- 적절한 보호 장비 선택 마스크 마스크를 효과적으로 사용하려면 마스크와 피부 사이에 틈이 생기지 않도록 얼굴에 밀착시켜야 합니다. 또한 귀에만 거는 형태보다는 2줄
- 상표명 '르네상스'는 작물 '고추(단고추류 포함)'의 '탄저병'에 사용하는 살균제이다. 품목명은 디페노코나졸.테부코나졸 분산성액제이다. 주성분(일반명)은 Dife
- 상표명 '실루엣'는 작물 '벼'의 '전착효과'에 사용하는 기타제이다. 품목명은 실록세인 액제이다. 주성분(일반명)은 Siloxane(함량 30%)이다. 인축독성은

=== EnsembleRetriever ===
- 상표명 '코어탄'는 작물 '고추'의 '탄저병'에 사용하는 살균제이다. 품목명은 테부코나졸 유제이다. 주성분(일반명)은 Tebuconazole(함량 25%)이다.
- 적절한 보호 장비 선택 마스크 마스크를 효과적으로 사용하려면 마스크와 피부 사이에 틈이 생기지 않도록 얼굴에 밀착시켜야 합니다. 또한 귀에만 거는 형태보다는 2줄
- 상표명 '르네상스'는 작물 '고추(단고추류 포함)'의 '탄저병'에 사용하는 살균제이다. 품목명은 디페노코나졸.테부코나졸 분산성액제이다. 주성분(일반명)은 Dife
- 상표명 '실루엣'는 작물 '벼'의 '전착효과'에 사용하는 기타제이다. 품목명은 실록세인 액제이다. 주성분(일반명)은 Siloxane(함량 30%)이다. 인축독성은

=== Hybrid 답변 ===
고추 탄저병에 사용할 수 있는 저독성 제품은 '코어탄'과 '르네상스'입니다. 두 제품의 회사와 안전사용시기는 다음과 같습니다:

1. '코어탄': 회사는 빅스타네이처사이언스(주), 안전사용시기는 수확 2일 전입니다.
2. '르네상스': 회사는 (주)한얼싸이언스, 안전사용시기는 수확 3일 전입니다.

근거 유형: 제품목록

## 6. 종합 비교

같은 질문 집합을 Naive / Graph / Agentic / CRAG / Fusion에 넣고 근거 유형·소요시간·답을 나란히 본다.  
(이미 실행한 결과는 재사용하고, 없는 항목만 추가로 호출한다.)

In [21]:
# 같은 질문으로 다섯 전략을 다시 돌려 답 요약과 소요시간을 한 표에 모은다.
compare_questions = [
    query_fact,
    query_multi,
    "농약 중독 시 응급처치법은?",
    "고충에 탄저 올때 저독성으로 뭐 뿌림?",
]


# 함수 실행 결과와 경과 초를 함께 반환한다.
def timed(fn, *args, **kwargs):
    t0 = time.time()
    out = fn(*args, **kwargs)
    return out, time.time() - t0


rows = []
for q in compare_questions:
    naive_out, t_n = timed(naive_rag, q)
    graph_out, t_g = timed(graph_rag, q)
    agent_out, t_a = timed(run_agentic_rag, q, verbose=False)
    crag_out, t_c = timed(run_self_corrective_rag, q, verbose=False)
    fus_out, t_f = timed(rag_fusion, q, n_variations=3)

    def short(text: str, n: int = 90) -> str:
        text = " ".join(str(text).split())
        return text if len(text) <= n else text[:n] + "..."

    rows.append(
        {
            "질문": q,
            "Naive": short(naive_out["answer"]),
            "Naive_s": round(t_n, 1),
            "Graph": short(graph_out["answer"]),
            "Graph_s": round(t_g, 1),
            "Agentic": short(agent_out),
            "Agentic_s": round(t_a, 1),
            "CRAG": short(crag_out),
            "CRAG_s": round(t_c, 1),
            "Fusion": short(fus_out["answer"]),
            "Fusion_s": round(t_f, 1),
        }
    )
    print(f"비교 완료: {q}")

compare_df = pd.DataFrame(rows)
pd.set_option("display.max_colwidth", 80)
compare_df

비교 완료: 상표명 경탄의 주성분과 회사는?
비교 완료: 고추 탄저병에 사용할 수 있는 저독성 제품의 회사와 안전사용시기는?
비교 완료: 농약 중독 시 응급처치법은?
비교 완료: 고충에 탄저 올때 저독성으로 뭐 뿌림?

,질문,Naive,Naive_s,Graph,Graph_s,Agentic,Agentic_s,CRAG,CRAG_s,Fusion,Fusion_s
0,상표명 경탄의 주성분과 회사는?,"상표명 '경탄'의 주성분은 Chlorothalonil+Kresoxim-methyl(함량 42(35+7)%)이며, 회사는 (주)농협케미컬입...",1.0,"상표명 경탄의 주성분은 Chlorothalonil과 Kresoxim-methyl이며, 제조사는 (주)농협케미컬입니다.",0.8,"상표명 ""경탄""의 주성분은 Chlorothalonil과 Kresoxim-methyl의 혼합물로, 함량은 42% (35% + 7%)입니다....",2.3,"상표명 '경탄'의 주성분은 Chlorothalonil+Kresoxim-methyl(함량 42(35+7)%)이며, 회사는 (주)농협케미컬입...",3.4,"상표명 '경탄'의 주성분은 Chlorothalonil+Kresoxim-methyl(함량 42(35+7)%)이며, 회사는 (주)농협케미컬입...",2.4
1,고추 탄저병에 사용할 수 있는 저독성 제품의 회사와 안전사용시기는?,"고추 탄저병에 사용할 수 있는 저독성 제품은 다음과 같습니다: 1. '코어탄' - 회사: 빅스타네이처사이언스(주), 안전사용시기: 수확2...",2.2,"고추 탄저병에 사용할 수 있는 저독성 제품은 '경탄'입니다. 이 제품은 (주)농협케미컬에서 제조하였으며, 안전 사용 시기는 수확 3일 전...",1.1,고추 탄저병에 사용할 수 있는 저독성 제품으로는 다음과 같은 것들이 있습니다: 1. **경탄** - 제조사: 농협케미컬 - 독성 등급: ...,3.5,"고추 탄저병에 사용할 수 있는 저독성 제품은 다음과 같습니다: 1. '코어탄' - 회사: 빅스타네이처사이언스(주), 안전사용시기: 수확2...",4.5,"고추 탄저병에 사용할 수 있는 저독성 제품은 다음과 같습니다: 1. '코어탄' - 회사: 빅스타네이처사이언스(주), 안전사용시기: 수확2...",3.5
2,농약 중독 시 응급처치법은?,주어진 자료만으로는 알 수 없다. 근거 유형: 안전사용 웹문서,0.9,주어진 자료만으로는 알 수 없다.,0.5,농약 중독 시 응급처치법은 다음과 같습니다: 1. **농약 종류 확인**: 중독된 사람이 어떤 종류의 농약에 중독되었는지를 확인합니다. ...,3.3,농약에 중독된 경우 응급처치법은 다음과 같습니다: 1. 중독된 농약의 종류를 확인합니다. 이는 올바른 조치를 취하는 데 중요합니다. 2....,11.0,농약에 중독된 사람이 있는 경우 응급처치 전에 어떤 종류의 농약에 중독되었는지를 알아야 올바른 조치를 할 수 있습니다. 중독된 사람이 의...,3.0
3,고충에 탄저 올때 저독성으로 뭐 뿌림?,"고추의 탄저병에 사용할 수 있는 저독성 살균제는 '코어탄'입니다. 이 제품은 테부코나졸 유제로, 인축독성이 Ⅳ급(저독성)입니다. 근거 유...",1.1,주어진 자료만으로는 알 수 없다.,0.8,고추의 탄저병에 저독성 농약으로 사용할 수 있는 제품은 다음과 같습니다: 1. **경탄** - **용도**: 살균제 - **주성분**: ...,4.5,"고추의 탄저병에 사용할 수 있는 저독성 살균제는 '코어탄'입니다. 이 제품은 테부코나졸 유제로, 주성분은 Tebuconazole(함량 2...",3.4,"고추의 탄저병에 사용할 수 있는 저독성 농약으로는 '코어탄'과 '총명탄'이 있습니다. 두 제품 모두 인축독성이 Ⅳ급(저독성)이며, 사용적...",4.1

### 상황별 추천 전략

| 상황 | 추천 | 이유 |
|---|---|---|
| 상표명·주성분 등 단일 사실 | Naive Vector RAG | 구현이 단순하고 표현이 겹치면 top-k로 충분하다. |
| 작물·병해충·독성·회사를 이어서 묻는 멀티홉 | Graph RAG | 관계가 엣지로 명시되어 있어 연결 고리 문장이 누락되지 않는다. |
| 질문 유형이 섞이거나(제품+안전), 개체명이 불명확 | Agentic RAG | 도구를 조합·재시도할 수 있다. 호출 횟수만큼 지연·비용이 는다. |
| 구어체·오탈자, 내부 KB에 없는 안전 지식 | Self-Corrective RAG | 채점·재작성 후 웹 문서로 전환한다. 채점 LLM 호출이 추가된다. |
| 한 질문에 제품 정보와 안전 수칙이 함께 들어 있음 | RAG Fusion / Hybrid | 질의 변형과 BM25가 서로 다른 문서를 끌어와 RRF로 보완한다. |

**구현 포인트 정리**

- 엑셀 전량 임베딩·전량 LLM 트리플 추출은 하지 않았다. 작물 5종 × 상표 25개의 규칙 기반 트리플만 그래프에 넣었다.
- 웹 문서는 벡터 검색(및 CRAG 외부 지식, Fusion 후보)으로만 썼다. 비정형 안전 수칙은 그래프보다 청크 검색이 맞다.
- 모든 생성은 grounded 프롬프트로, 근거가 없으면 모른다고 답하게 했다.
- API 키는 `C:\env\.env`에서만 로드했고 출력하지 않았다.